modLoader = "javafml"
loaderVersion = "[39,)"
license = "All rights reserved"
[[mods]]
modId = "jerintegration"
version = "${file.jarVersion}"
displayName = "JER Integration"
credits = "Mezz for JEI, Way2Muchnoise for JER"
authors = "AlasDiablo"
description = '''
JER Integration for other mod
'''
[[dependencies.jerintegration]]
    modId = "forge"
    mandatory = true
    versionRange = "[39,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.jerintegration]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.1,1.19)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.jerintegration]]
    modId = "jei"
    mandatory = true
    versionRange = "[9.2.1.69,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.jerintegration]]
    modId = "jeresources"
mandatory = true
versionRange = "[0.13.1.138,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.jerintegration]]
modId = "ae2"
mandatory = false
versionRange = "[10.0.0-beta.4,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.jerintegration]]
modId = "create"
mandatory = false
versionRange = "[0.4d,)"
ordering = "AFTER"
side = "BOTH"

