modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
[[mods]]
modId = "jerintegration"
version = "${file.jarVersion}"
displayName = "JER Integration"
credits = "Mezz for JEI, Way2Muchnoise for JER"
authors = "AlasDiablo"
description = '''
JER Integration for other mod
'''
[[dependencies.jerintegration]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.jerintegration]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.1,1.19)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.jerintegration]]
    modId = "jei"
    mandatory = true
    versionRange = "[9.5.5.174,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.jerintegration]]
    modId = "jeresources"
    mandatory = true
    versionRange = "[0.14.1.160,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.jerintegration]]
    modId = "ae2"
    mandatory = false
    versionRange = "[11.0.0-alpha.3,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.jerintegration]]
    modId = "immersiveengineering"
    mandatory = false
    versionRange = "[1.18.2-8.0.0-146,)"
    ordering = "AFTER"
    side = "BOTH"

